spring:
  datasource: 
    url: jdbc:mysql://192.168.0.106:3306/moty_note?characterEncoding=utf-8&useSSL=false
    username: moty
    password: zxcv1234
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.myself.mybatis.entity